name: Playwright Test with Allure Report

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Run Playwright tests
      - name: Run Playwright tests
        run: |
          npx playwright test

      # Step 5: Install Allure CLI
      - name: Install Allure Commandline
        run: |
          npm install -g allure-commandline

      # Step 6: Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      # Step 7: Upload the Allure report as an artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
